# 应用服务 WEB 访问端口
server:
  port: 8081
  servlet:
    context-path: /api

#内部openid
api:
  client:
    access-key: xuqing
    secret-key: a1b2c3d4

#外部openid
openId:
  weather: b91ba70e7e1e088818f64a3465780ba4
  deilyEnglish: ca87ef4b24035f6d4bb4426eca6df6f7

